baseurl: 
title: Carl Simpson, Macroevolution
subtitle:
author: Carl Simpson
simple_search: http://google.com/search

analytics :
  provider : google
  google : 
      tracking_id : 'UA-52984046-1'

description: 
name: Carl Simpson
markdown: Kramdown
kramdown:  
  input: GFM

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
syntax_highlighter: rouge
titlecase: true
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: subl
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/git-pages/simpson-homwbrewed/
